env: &env
    docker:
      - image: satoshikumano/ubuntu-18.04-cpp:0.0.1
version: 2
jobs:
  build:
    <<: *env
    steps:
      - checkout
      - run:
          name: make build
          command: make build
      - store_artifacts:
          path: kii/libkiisdk.so
          destination: libkiisdk.so
      - run:
          name: make doc
          command: make doc
      - store_artifacts:
          path: kii/html
          destination: html
      - persist_to_workspace:
          root: .
          paths: kii/html

  doc-all:
    <<: *env
    steps:
      - checkout
      - run:
          name: Checkout doc repo.
          command: git clone git@github.com:KiiPlatform/ebisu-doc.git
      - run:
          name: Build docs
          command: |
            make -C khc clean doc
            make -C kii clean doc
            make -C jkii clean doc
            make -C tio clean doc
      - run:
          name: Copy docs
          command: |
            rsync -rR --delete khc/html ebisu-doc
            rsync -rR --delete kii/html ebisu-doc
            rsync -rR --delete jkii/html ebisu-doc
            rsync -rR --delete tio/html ebisu-doc
      - run:
          name: Commit changes
          command: |
            cd ebisu-doc
            git config user.email "satoshi.kumano@kii.com"
            git config user.name "Satoshi Kumano"
            git add .
            git commit -m 'Updated ebisu docs.'
            git push origin master

  stest-khc:
    <<: *env
    steps:
      - checkout
      - run:
          name: khc small test
          command: MEMCHECK=1 JUNIT=1 make stest-khc
      - store_test_results:
          path: tests/small_test/khc/test-results
      - store_artifacts:
          path: tests/small_test/khc/tmp_random_chunk_response.txt

  stest-jkii:
    <<: *env
    steps:
      - checkout
      - run:
          name: jkii small test
          command: MEMCHECK=1 JUNIT=1 make stest-jkii
      - store_test_results:
          path: tests/small_test/jkii/test-results

  stest-kii:
    <<: *env
    steps:
      - checkout
      - run:
          name: kii small test
          command: MEMCHECK=1 JUNIT=1 make stest-kii
      - store_test_results:
          path: tests/small_test/kii/test-results

  stest-tio:
    <<: *env
    steps:
      - checkout
      - run:
          name: tio small test
          command: MEMCHECK=1 JUNIT=1 make stest-tio
      - store_test_results:
          path: tests/small_test/tio/test-results

  ltest-khc:
    <<: *env
    steps:
      - checkout
      - run:
          name: khc large test
          command: MEMCHECK=1 JUNIT=1 make ltest-khc
      - store_test_results:
          path: tests/large_test/khc/test-results

  ltest-kii:
    <<: *env
    steps:
      - checkout
      - run:
          name: kii large test
          command: make ltest-kii
      - store_test_results:
          path: tests/large_test/kii/test-results

workflows:
  version: 2
  default:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
      - stest-khc:
          filters:
            branches:
              ignore:
                - gh-pages
      - stest-jkii:
          filters:
            branches:
              ignore:
                - gh-pages
      - stest-kii:
          filters:
            branches:
              ignore:
                - gh-pages
      - stest-tio:
          filters:
            branches:
              ignore:
                - gh-pages
      - ltest-khc:
          filters:
            branches:
              ignore:
                - gh-pages
      - ltest-kii:
          filters:
            branches:
              ignore:
                - gh-pages
      - doc-all:
          filters:
            branches:
              only: master

# vim: set sts=2 sw=2 et:

