all:
	mkdir -p custom/tio
	cp ../../jkii/src/*.c custom/tio
	cp ../../jkii/include/*.h custom/tio
	cp ../../jkii/libs/jsmn/*.c custom/tio
	cp ../../jkii/libs/jsmn/*.h custom/tio
	cp ../../khc/src/*.c custom/tio
	cp ../../khc/src/*.h custom/tio
	cp ../../khc/include/*.h custom/tio
	cp ../../kii/*.c custom/tio
	cp ../../kii/*.h custom/tio
	cp ../../kii/include/*.h custom/tio
	cp ../*.c custom/tio
	cp ../*.h custom/tio
	cp ../include/*.h custom/tio
	cp ./*.c custom
	cp ./*.h custom

clean:
	rm -rf custom

.PHONY: all
